-- MySQL Script generated by MySQL Workbench
-- Thu Apr  6 10:35:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spider
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spider` ;

-- -----------------------------------------------------
-- Schema spider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spider` DEFAULT CHARACTER SET utf8 ;
USE `spider` ;

-- -----------------------------------------------------
-- Table `spider`.`model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spider`.`model` ;

CREATE TABLE IF NOT EXISTS `spider`.`model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL COMMENT '产品名称',
  `md5` VARCHAR(32) NULL COMMENT '地址的URL加密(md5)，用来判断数据是否采集过',
  `url` VARCHAR(1000) NULL COMMENT '采集地址',
  `num` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '采集的次数，每采集一次加一',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_md5` (`md5` ASC),
  UNIQUE INDEX `unique_url` (`url` ASC));


-- -----------------------------------------------------
-- Table `spider`.`platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spider`.`platform` ;

CREATE TABLE IF NOT EXISTS `spider`.`platform` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL COMMENT '平台名称',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '平台表';


-- -----------------------------------------------------
-- Table `spider`.`model_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spider`.`model_info` ;

CREATE TABLE IF NOT EXISTS `spider`.`model_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model_id` INT NOT NULL COMMENT '商品的id',
  `platform_id` INT NOT NULL COMMENT '平台的id，一件商品只能归属一个平台',
  `original_price` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '原始价格，默认为0',
  `reseller` VARCHAR(255) NULL DEFAULT '' COMMENT '销售网站',
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '折扣价格，保留2位小数，默认为0',
  `in_stock` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '库存，默认为0',
  `fast_delivery` VARCHAR(255) NULL DEFAULT '',
  `free_shipping` VARCHAR(255) NULL DEFAULT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_model_info_model_idx` (`model_id` ASC),
  INDEX `fk_model_info_platform1_idx` (`platform_id` ASC),
  CONSTRAINT `fk_model_info_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `spider`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_model_info_platform1`
    FOREIGN KEY (`platform_id`)
    REFERENCES `spider`.`platform` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
